/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateInput {
  'id' : bigint,
  'aktif' : boolean,
  'nama' : string,
  'email' : string,
  'wilayah' : string,
}
export interface CreateInput__1 {
  'id' : bigint,
  'penulis' : string,
  'tanggal' : string,
  'ringkasan' : string,
  'judul' : string,
  'kategori' : string,
  'gambarUrl' : string,
  'konten' : string,
}
export interface CreateInput__2 {
  'id' : bigint,
  'status' : Status,
  'topik' : Topik,
  'tanggal' : string,
  'nama' : string,
  'judul' : string,
  'deskripsi' : string,
  'catatan' : string,
  'kontak' : string,
}
export interface CreateInput__3 {
  'id' : bigint,
  'status' : Status__1,
  'sudahDivalidasi' : boolean,
  'jenisBantuan' : string,
  'koordinatLat' : number,
  'koordinatLng' : number,
  'alamat' : string,
  'jumlahBantuan' : bigint,
  'tanggal' : string,
  'nama' : string,
  'wilayah' : string,
  'validatorId' : [] | [string],
  'keperluanBantuan' : string,
  'catatan' : string,
}
export interface CreateInput__4 {
  'id' : bigint,
  'linkLabel' : string,
  'linkUrl' : string,
  'order' : bigint,
}
export type Status = { 'diproses' : null } |
  { 'baru' : null } |
  { 'selesai' : null };
export type Status__1 = { 'diproses' : null } |
  { 'menunggu' : null } |
  { 'didistribusikan' : null };
export interface T {
  'id' : bigint,
  'aktif' : boolean,
  'nama' : string,
  'email' : string,
  'wilayah' : string,
}
export interface T__1 {
  'id' : bigint,
  'penulis' : string,
  'tanggal' : string,
  'ringkasan' : string,
  'judul' : string,
  'kategori' : string,
  'gambarUrl' : string,
  'konten' : string,
}
export interface T__2 {
  'id' : bigint,
  'status' : Status,
  'topik' : Topik,
  'tanggal' : string,
  'nama' : string,
  'judul' : string,
  'deskripsi' : string,
  'catatan' : string,
  'kontak' : string,
}
export interface T__3 {
  'id' : bigint,
  'status' : Status__1,
  'sudahDivalidasi' : boolean,
  'jenisBantuan' : string,
  'koordinatLat' : number,
  'koordinatLng' : number,
  'alamat' : string,
  'jumlahBantuan' : bigint,
  'tanggal' : string,
  'nama' : string,
  'wilayah' : string,
  'validatorId' : [] | [string],
  'keperluanBantuan' : string,
  'catatan' : string,
}
export interface T__4 {
  'id' : bigint,
  'linkLabel' : string,
  'linkUrl' : string,
  'order' : bigint,
}
export type Topik = { 'lainnya' : null } |
  { 'bantuan' : null } |
  { 'pengungsian' : null } |
  { 'infrastruktur' : null } |
  { 'bencana' : null } |
  { 'kesehatan' : null };
export interface UpdateInput {
  'id' : bigint,
  'aktif' : boolean,
  'nama' : string,
  'email' : string,
  'wilayah' : string,
}
export interface UpdateInput__1 {
  'id' : bigint,
  'penulis' : string,
  'tanggal' : string,
  'ringkasan' : string,
  'judul' : string,
  'kategori' : string,
  'gambarUrl' : string,
  'konten' : string,
}
export interface UpdateInput__2 {
  'id' : bigint,
  'status' : Status,
  'topik' : Topik,
  'tanggal' : string,
  'nama' : string,
  'judul' : string,
  'deskripsi' : string,
  'catatan' : string,
  'kontak' : string,
}
export interface UpdateInput__3 {
  'id' : bigint,
  'status' : Status__1,
  'sudahDivalidasi' : boolean,
  'jenisBantuan' : string,
  'koordinatLat' : number,
  'koordinatLng' : number,
  'alamat' : string,
  'jumlahBantuan' : bigint,
  'tanggal' : string,
  'nama' : string,
  'wilayah' : string,
  'validatorId' : [] | [string],
  'keperluanBantuan' : string,
  'catatan' : string,
}
export interface UpdateInput__4 {
  'id' : bigint,
  'linkLabel' : string,
  'linkUrl' : string,
  'order' : bigint,
}
export interface _SERVICE {
  'addFooterLink' : ActorMethod<[CreateInput__4], undefined>,
  'addPenerimaBantuan' : ActorMethod<[CreateInput__3], undefined>,
  'addPengaduan' : ActorMethod<[CreateInput__2], undefined>,
  'addPublikasi' : ActorMethod<[CreateInput__1], undefined>,
  'addValidator' : ActorMethod<[CreateInput], undefined>,
  'deleteFooterLink' : ActorMethod<[bigint], undefined>,
  'deletePenerimaBantuan' : ActorMethod<[bigint], undefined>,
  'deletePengaduan' : ActorMethod<[bigint], undefined>,
  'deletePublikasi' : ActorMethod<[bigint], undefined>,
  'deleteValidator' : ActorMethod<[bigint], undefined>,
  'getAllFooterLinks' : ActorMethod<[], Array<T__4>>,
  'getAllPenerimaBantuan' : ActorMethod<[], Array<T__3>>,
  'getAllPengaduan' : ActorMethod<[], Array<T__2>>,
  'getAllPublikasi' : ActorMethod<[], Array<T__1>>,
  'getAllValidators' : ActorMethod<[], Array<T>>,
  'getFooterLinkById' : ActorMethod<[bigint], T__4>,
  'getPenerimaBantuanById' : ActorMethod<[bigint], T__3>,
  'getPenerimaBantuanByJenis' : ActorMethod<[string], Array<T__3>>,
  'getPenerimaBantuanByStatus' : ActorMethod<[Status__1], Array<T__3>>,
  'getPengaduanById' : ActorMethod<[bigint], T__2>,
  'getPublikasiById' : ActorMethod<[bigint], T__1>,
  'getValidatorById' : ActorMethod<[bigint], T>,
  'isAdmin' : ActorMethod<[string], boolean>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateFooterLink' : ActorMethod<[UpdateInput__4], undefined>,
  'updatePenerimaBantuan' : ActorMethod<[UpdateInput__3], undefined>,
  'updatePengaduan' : ActorMethod<[UpdateInput__2], undefined>,
  'updatePublikasi' : ActorMethod<[UpdateInput__1], undefined>,
  'updateValidator' : ActorMethod<[UpdateInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];