/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateInput__4 = IDL.Record({
  'id' : IDL.Nat,
  'linkLabel' : IDL.Text,
  'linkUrl' : IDL.Text,
  'order' : IDL.Nat,
});
export const Status__1 = IDL.Variant({
  'diproses' : IDL.Null,
  'menunggu' : IDL.Null,
  'didistribusikan' : IDL.Null,
});
export const CreateInput__3 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__1,
  'sudahDivalidasi' : IDL.Bool,
  'jenisBantuan' : IDL.Text,
  'koordinatLat' : IDL.Float64,
  'koordinatLng' : IDL.Float64,
  'alamat' : IDL.Text,
  'jumlahBantuan' : IDL.Nat,
  'tanggal' : IDL.Text,
  'nama' : IDL.Text,
  'wilayah' : IDL.Text,
  'validatorId' : IDL.Opt(IDL.Text),
  'keperluanBantuan' : IDL.Text,
  'catatan' : IDL.Text,
});
export const Status = IDL.Variant({
  'diproses' : IDL.Null,
  'baru' : IDL.Null,
  'selesai' : IDL.Null,
});
export const Topik = IDL.Variant({
  'lainnya' : IDL.Null,
  'bantuan' : IDL.Null,
  'pengungsian' : IDL.Null,
  'infrastruktur' : IDL.Null,
  'bencana' : IDL.Null,
  'kesehatan' : IDL.Null,
});
export const CreateInput__2 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'topik' : Topik,
  'tanggal' : IDL.Text,
  'nama' : IDL.Text,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
  'catatan' : IDL.Text,
  'kontak' : IDL.Text,
});
export const CreateInput__1 = IDL.Record({
  'id' : IDL.Nat,
  'penulis' : IDL.Text,
  'tanggal' : IDL.Text,
  'ringkasan' : IDL.Text,
  'judul' : IDL.Text,
  'kategori' : IDL.Text,
  'gambarUrl' : IDL.Text,
  'konten' : IDL.Text,
});
export const CreateInput = IDL.Record({
  'id' : IDL.Nat,
  'aktif' : IDL.Bool,
  'nama' : IDL.Text,
  'email' : IDL.Text,
  'wilayah' : IDL.Text,
});
export const T__5 = IDL.Record({
  'id' : IDL.Nat,
  'linkLabel' : IDL.Text,
  'linkUrl' : IDL.Text,
  'order' : IDL.Nat,
});
export const T__4 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__1,
  'sudahDivalidasi' : IDL.Bool,
  'jenisBantuan' : IDL.Text,
  'koordinatLat' : IDL.Float64,
  'koordinatLng' : IDL.Float64,
  'alamat' : IDL.Text,
  'jumlahBantuan' : IDL.Nat,
  'tanggal' : IDL.Text,
  'nama' : IDL.Text,
  'wilayah' : IDL.Text,
  'validatorId' : IDL.Opt(IDL.Text),
  'keperluanBantuan' : IDL.Text,
  'catatan' : IDL.Text,
});
export const T__3 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'topik' : Topik,
  'tanggal' : IDL.Text,
  'nama' : IDL.Text,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
  'catatan' : IDL.Text,
  'kontak' : IDL.Text,
});
export const T__2 = IDL.Record({
  'id' : IDL.Nat,
  'penulis' : IDL.Text,
  'tanggal' : IDL.Text,
  'ringkasan' : IDL.Text,
  'judul' : IDL.Text,
  'kategori' : IDL.Text,
  'gambarUrl' : IDL.Text,
  'konten' : IDL.Text,
});
export const T__1 = IDL.Record({
  'id' : IDL.Nat,
  'aktif' : IDL.Bool,
  'nama' : IDL.Text,
  'email' : IDL.Text,
  'wilayah' : IDL.Text,
});
export const T = IDL.Record({
  'alamat' : IDL.Text,
  'deskripsi' : IDL.Text,
  'email' : IDL.Text,
  'telepon' : IDL.Text,
  'namaOrganisasi' : IDL.Text,
  'copyright' : IDL.Text,
});
export const UpdateInput__4 = IDL.Record({
  'id' : IDL.Nat,
  'linkLabel' : IDL.Text,
  'linkUrl' : IDL.Text,
  'order' : IDL.Nat,
});
export const UpdateInput__3 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__1,
  'sudahDivalidasi' : IDL.Bool,
  'jenisBantuan' : IDL.Text,
  'koordinatLat' : IDL.Float64,
  'koordinatLng' : IDL.Float64,
  'alamat' : IDL.Text,
  'jumlahBantuan' : IDL.Nat,
  'tanggal' : IDL.Text,
  'nama' : IDL.Text,
  'wilayah' : IDL.Text,
  'validatorId' : IDL.Opt(IDL.Text),
  'keperluanBantuan' : IDL.Text,
  'catatan' : IDL.Text,
});
export const UpdateInput__2 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'topik' : Topik,
  'tanggal' : IDL.Text,
  'nama' : IDL.Text,
  'judul' : IDL.Text,
  'deskripsi' : IDL.Text,
  'catatan' : IDL.Text,
  'kontak' : IDL.Text,
});
export const UpdateInput__1 = IDL.Record({
  'id' : IDL.Nat,
  'penulis' : IDL.Text,
  'tanggal' : IDL.Text,
  'ringkasan' : IDL.Text,
  'judul' : IDL.Text,
  'kategori' : IDL.Text,
  'gambarUrl' : IDL.Text,
  'konten' : IDL.Text,
});
export const UpdateInput = IDL.Record({
  'id' : IDL.Nat,
  'aktif' : IDL.Bool,
  'nama' : IDL.Text,
  'email' : IDL.Text,
  'wilayah' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFooterLink' : IDL.Func([CreateInput__4], [], []),
  'addPenerimaBantuan' : IDL.Func([CreateInput__3], [], []),
  'addPengaduan' : IDL.Func([CreateInput__2], [], []),
  'addPublikasi' : IDL.Func([CreateInput__1], [], []),
  'addValidator' : IDL.Func([CreateInput], [], []),
  'deleteFooterLink' : IDL.Func([IDL.Nat], [], []),
  'deletePenerimaBantuan' : IDL.Func([IDL.Nat], [], []),
  'deletePengaduan' : IDL.Func([IDL.Nat], [], []),
  'deletePublikasi' : IDL.Func([IDL.Nat], [], []),
  'deleteValidator' : IDL.Func([IDL.Nat], [], []),
  'getAllFooterLinks' : IDL.Func([], [IDL.Vec(T__5)], ['query']),
  'getAllPenerimaBantuan' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
  'getAllPengaduan' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getAllPublikasi' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
  'getAllValidators' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getFooterInfo' : IDL.Func([], [T], ['query']),
  'getFooterLinkById' : IDL.Func([IDL.Nat], [T__5], ['query']),
  'getPenerimaBantuanById' : IDL.Func([IDL.Nat], [T__4], ['query']),
  'getPenerimaBantuanByJenis' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(T__4)],
      ['query'],
    ),
  'getPenerimaBantuanByStatus' : IDL.Func(
      [Status__1],
      [IDL.Vec(T__4)],
      ['query'],
    ),
  'getPengaduanById' : IDL.Func([IDL.Nat], [T__3], ['query']),
  'getPublikasiById' : IDL.Func([IDL.Nat], [T__2], ['query']),
  'getValidatorById' : IDL.Func([IDL.Nat], [T__1], ['query']),
  'isAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'updateFooterInfo' : IDL.Func([T], [], []),
  'updateFooterLink' : IDL.Func([UpdateInput__4], [], []),
  'updatePenerimaBantuan' : IDL.Func([UpdateInput__3], [], []),
  'updatePengaduan' : IDL.Func([UpdateInput__2], [], []),
  'updatePublikasi' : IDL.Func([UpdateInput__1], [], []),
  'updateValidator' : IDL.Func([UpdateInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateInput__4 = IDL.Record({
    'id' : IDL.Nat,
    'linkLabel' : IDL.Text,
    'linkUrl' : IDL.Text,
    'order' : IDL.Nat,
  });
  const Status__1 = IDL.Variant({
    'diproses' : IDL.Null,
    'menunggu' : IDL.Null,
    'didistribusikan' : IDL.Null,
  });
  const CreateInput__3 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__1,
    'sudahDivalidasi' : IDL.Bool,
    'jenisBantuan' : IDL.Text,
    'koordinatLat' : IDL.Float64,
    'koordinatLng' : IDL.Float64,
    'alamat' : IDL.Text,
    'jumlahBantuan' : IDL.Nat,
    'tanggal' : IDL.Text,
    'nama' : IDL.Text,
    'wilayah' : IDL.Text,
    'validatorId' : IDL.Opt(IDL.Text),
    'keperluanBantuan' : IDL.Text,
    'catatan' : IDL.Text,
  });
  const Status = IDL.Variant({
    'diproses' : IDL.Null,
    'baru' : IDL.Null,
    'selesai' : IDL.Null,
  });
  const Topik = IDL.Variant({
    'lainnya' : IDL.Null,
    'bantuan' : IDL.Null,
    'pengungsian' : IDL.Null,
    'infrastruktur' : IDL.Null,
    'bencana' : IDL.Null,
    'kesehatan' : IDL.Null,
  });
  const CreateInput__2 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'topik' : Topik,
    'tanggal' : IDL.Text,
    'nama' : IDL.Text,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
    'catatan' : IDL.Text,
    'kontak' : IDL.Text,
  });
  const CreateInput__1 = IDL.Record({
    'id' : IDL.Nat,
    'penulis' : IDL.Text,
    'tanggal' : IDL.Text,
    'ringkasan' : IDL.Text,
    'judul' : IDL.Text,
    'kategori' : IDL.Text,
    'gambarUrl' : IDL.Text,
    'konten' : IDL.Text,
  });
  const CreateInput = IDL.Record({
    'id' : IDL.Nat,
    'aktif' : IDL.Bool,
    'nama' : IDL.Text,
    'email' : IDL.Text,
    'wilayah' : IDL.Text,
  });
  const T__5 = IDL.Record({
    'id' : IDL.Nat,
    'linkLabel' : IDL.Text,
    'linkUrl' : IDL.Text,
    'order' : IDL.Nat,
  });
  const T__4 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__1,
    'sudahDivalidasi' : IDL.Bool,
    'jenisBantuan' : IDL.Text,
    'koordinatLat' : IDL.Float64,
    'koordinatLng' : IDL.Float64,
    'alamat' : IDL.Text,
    'jumlahBantuan' : IDL.Nat,
    'tanggal' : IDL.Text,
    'nama' : IDL.Text,
    'wilayah' : IDL.Text,
    'validatorId' : IDL.Opt(IDL.Text),
    'keperluanBantuan' : IDL.Text,
    'catatan' : IDL.Text,
  });
  const T__3 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'topik' : Topik,
    'tanggal' : IDL.Text,
    'nama' : IDL.Text,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
    'catatan' : IDL.Text,
    'kontak' : IDL.Text,
  });
  const T__2 = IDL.Record({
    'id' : IDL.Nat,
    'penulis' : IDL.Text,
    'tanggal' : IDL.Text,
    'ringkasan' : IDL.Text,
    'judul' : IDL.Text,
    'kategori' : IDL.Text,
    'gambarUrl' : IDL.Text,
    'konten' : IDL.Text,
  });
  const T__1 = IDL.Record({
    'id' : IDL.Nat,
    'aktif' : IDL.Bool,
    'nama' : IDL.Text,
    'email' : IDL.Text,
    'wilayah' : IDL.Text,
  });
  const T = IDL.Record({
    'alamat' : IDL.Text,
    'deskripsi' : IDL.Text,
    'email' : IDL.Text,
    'telepon' : IDL.Text,
    'namaOrganisasi' : IDL.Text,
    'copyright' : IDL.Text,
  });
  const UpdateInput__4 = IDL.Record({
    'id' : IDL.Nat,
    'linkLabel' : IDL.Text,
    'linkUrl' : IDL.Text,
    'order' : IDL.Nat,
  });
  const UpdateInput__3 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__1,
    'sudahDivalidasi' : IDL.Bool,
    'jenisBantuan' : IDL.Text,
    'koordinatLat' : IDL.Float64,
    'koordinatLng' : IDL.Float64,
    'alamat' : IDL.Text,
    'jumlahBantuan' : IDL.Nat,
    'tanggal' : IDL.Text,
    'nama' : IDL.Text,
    'wilayah' : IDL.Text,
    'validatorId' : IDL.Opt(IDL.Text),
    'keperluanBantuan' : IDL.Text,
    'catatan' : IDL.Text,
  });
  const UpdateInput__2 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'topik' : Topik,
    'tanggal' : IDL.Text,
    'nama' : IDL.Text,
    'judul' : IDL.Text,
    'deskripsi' : IDL.Text,
    'catatan' : IDL.Text,
    'kontak' : IDL.Text,
  });
  const UpdateInput__1 = IDL.Record({
    'id' : IDL.Nat,
    'penulis' : IDL.Text,
    'tanggal' : IDL.Text,
    'ringkasan' : IDL.Text,
    'judul' : IDL.Text,
    'kategori' : IDL.Text,
    'gambarUrl' : IDL.Text,
    'konten' : IDL.Text,
  });
  const UpdateInput = IDL.Record({
    'id' : IDL.Nat,
    'aktif' : IDL.Bool,
    'nama' : IDL.Text,
    'email' : IDL.Text,
    'wilayah' : IDL.Text,
  });
  
  return IDL.Service({
    'addFooterLink' : IDL.Func([CreateInput__4], [], []),
    'addPenerimaBantuan' : IDL.Func([CreateInput__3], [], []),
    'addPengaduan' : IDL.Func([CreateInput__2], [], []),
    'addPublikasi' : IDL.Func([CreateInput__1], [], []),
    'addValidator' : IDL.Func([CreateInput], [], []),
    'deleteFooterLink' : IDL.Func([IDL.Nat], [], []),
    'deletePenerimaBantuan' : IDL.Func([IDL.Nat], [], []),
    'deletePengaduan' : IDL.Func([IDL.Nat], [], []),
    'deletePublikasi' : IDL.Func([IDL.Nat], [], []),
    'deleteValidator' : IDL.Func([IDL.Nat], [], []),
    'getAllFooterLinks' : IDL.Func([], [IDL.Vec(T__5)], ['query']),
    'getAllPenerimaBantuan' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
    'getAllPengaduan' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getAllPublikasi' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
    'getAllValidators' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getFooterInfo' : IDL.Func([], [T], ['query']),
    'getFooterLinkById' : IDL.Func([IDL.Nat], [T__5], ['query']),
    'getPenerimaBantuanById' : IDL.Func([IDL.Nat], [T__4], ['query']),
    'getPenerimaBantuanByJenis' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(T__4)],
        ['query'],
      ),
    'getPenerimaBantuanByStatus' : IDL.Func(
        [Status__1],
        [IDL.Vec(T__4)],
        ['query'],
      ),
    'getPengaduanById' : IDL.Func([IDL.Nat], [T__3], ['query']),
    'getPublikasiById' : IDL.Func([IDL.Nat], [T__2], ['query']),
    'getValidatorById' : IDL.Func([IDL.Nat], [T__1], ['query']),
    'isAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'updateFooterInfo' : IDL.Func([T], [], []),
    'updateFooterLink' : IDL.Func([UpdateInput__4], [], []),
    'updatePenerimaBantuan' : IDL.Func([UpdateInput__3], [], []),
    'updatePengaduan' : IDL.Func([UpdateInput__2], [], []),
    'updatePublikasi' : IDL.Func([UpdateInput__1], [], []),
    'updateValidator' : IDL.Func([UpdateInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };