/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateInput__1 {
    id: bigint;
    penulis: string;
    tanggal: string;
    ringkasan: string;
    judul: string;
    kategori: string;
    gambarUrl: string;
    konten: string;
}
export interface UpdateInput__1 {
    id: bigint;
    penulis: string;
    tanggal: string;
    ringkasan: string;
    judul: string;
    kategori: string;
    gambarUrl: string;
    konten: string;
}
export interface T__1 {
    id: bigint;
    penulis: string;
    tanggal: string;
    ringkasan: string;
    judul: string;
    kategori: string;
    gambarUrl: string;
    konten: string;
}
export interface CreateInput__2 {
    id: bigint;
    status: Status;
    topik: Topik;
    tanggal: string;
    nama: string;
    judul: string;
    deskripsi: string;
    catatan: string;
    kontak: string;
}
export interface UpdateInput__4 {
    id: bigint;
    linkLabel: string;
    linkUrl: string;
    order: bigint;
}
export interface T__4 {
    id: bigint;
    linkLabel: string;
    linkUrl: string;
    order: bigint;
}
export interface UpdateInput__2 {
    id: bigint;
    status: Status;
    topik: Topik;
    tanggal: string;
    nama: string;
    judul: string;
    deskripsi: string;
    catatan: string;
    kontak: string;
}
export interface UpdateInput {
    id: bigint;
    aktif: boolean;
    nama: string;
    email: string;
    wilayah: string;
}
export interface T__3 {
    id: bigint;
    status: Status__1;
    sudahDivalidasi: boolean;
    jenisBantuan: string;
    koordinatLat: number;
    koordinatLng: number;
    alamat: string;
    jumlahBantuan: bigint;
    tanggal: string;
    nama: string;
    wilayah: string;
    validatorId?: string;
    keperluanBantuan: string;
    catatan: string;
}
export interface CreateInput__3 {
    id: bigint;
    status: Status__1;
    sudahDivalidasi: boolean;
    jenisBantuan: string;
    koordinatLat: number;
    koordinatLng: number;
    alamat: string;
    jumlahBantuan: bigint;
    tanggal: string;
    nama: string;
    wilayah: string;
    validatorId?: string;
    keperluanBantuan: string;
    catatan: string;
}
export interface T__2 {
    id: bigint;
    status: Status;
    topik: Topik;
    tanggal: string;
    nama: string;
    judul: string;
    deskripsi: string;
    catatan: string;
    kontak: string;
}
export interface T {
    id: bigint;
    aktif: boolean;
    nama: string;
    email: string;
    wilayah: string;
}
export interface UpdateInput__3 {
    id: bigint;
    status: Status__1;
    sudahDivalidasi: boolean;
    jenisBantuan: string;
    koordinatLat: number;
    koordinatLng: number;
    alamat: string;
    jumlahBantuan: bigint;
    tanggal: string;
    nama: string;
    wilayah: string;
    validatorId?: string;
    keperluanBantuan: string;
    catatan: string;
}
export interface CreateInput {
    id: bigint;
    aktif: boolean;
    nama: string;
    email: string;
    wilayah: string;
}
export interface CreateInput__4 {
    id: bigint;
    linkLabel: string;
    linkUrl: string;
    order: bigint;
}
export enum Status {
    diproses = "diproses",
    baru = "baru",
    selesai = "selesai"
}
export enum Status__1 {
    diproses = "diproses",
    menunggu = "menunggu",
    didistribusikan = "didistribusikan"
}
export enum Topik {
    lainnya = "lainnya",
    bantuan = "bantuan",
    pengungsian = "pengungsian",
    infrastruktur = "infrastruktur",
    bencana = "bencana",
    kesehatan = "kesehatan"
}
export interface backendInterface {
    addFooterLink(input: CreateInput__4): Promise<void>;
    addPenerimaBantuan(input: CreateInput__3): Promise<void>;
    addPengaduan(input: CreateInput__2): Promise<void>;
    addPublikasi(input: CreateInput__1): Promise<void>;
    addValidator(input: CreateInput): Promise<void>;
    deleteFooterLink(id: bigint): Promise<void>;
    deletePenerimaBantuan(id: bigint): Promise<void>;
    deletePengaduan(id: bigint): Promise<void>;
    deletePublikasi(id: bigint): Promise<void>;
    deleteValidator(id: bigint): Promise<void>;
    getAllFooterLinks(): Promise<Array<T__4>>;
    getAllPenerimaBantuan(): Promise<Array<T__3>>;
    getAllPengaduan(): Promise<Array<T__2>>;
    getAllPublikasi(): Promise<Array<T__1>>;
    getAllValidators(): Promise<Array<T>>;
    getFooterLinkById(id: bigint): Promise<T__4>;
    getPenerimaBantuanById(id: bigint): Promise<T__3>;
    getPenerimaBantuanByJenis(jenis: string): Promise<Array<T__3>>;
    getPenerimaBantuanByStatus(status: Status__1): Promise<Array<T__3>>;
    getPengaduanById(id: bigint): Promise<T__2>;
    getPublikasiById(id: bigint): Promise<T__1>;
    getValidatorById(id: bigint): Promise<T>;
    isAdmin(password: string): Promise<boolean>;
    seedSampleData(): Promise<void>;
    updateFooterLink(input: UpdateInput__4): Promise<void>;
    updatePenerimaBantuan(input: UpdateInput__3): Promise<void>;
    updatePengaduan(input: UpdateInput__2): Promise<void>;
    updatePublikasi(input: UpdateInput__1): Promise<void>;
    updateValidator(input: UpdateInput): Promise<void>;
}
import type { CreateInput__2 as _CreateInput__2, CreateInput__3 as _CreateInput__3, Status as _Status, Status__1 as _Status__1, T__2 as _T__2, T__3 as _T__3, Topik as _Topik, UpdateInput__2 as _UpdateInput__2, UpdateInput__3 as _UpdateInput__3 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFooterLink(arg0: CreateInput__4): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFooterLink(arg0);
            return result;
        }
    }
    async addPenerimaBantuan(arg0: CreateInput__3): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPenerimaBantuan(to_candid_CreateInput__3_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPenerimaBantuan(to_candid_CreateInput__3_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPengaduan(arg0: CreateInput__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPengaduan(to_candid_CreateInput__2_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPengaduan(to_candid_CreateInput__2_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPublikasi(arg0: CreateInput__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPublikasi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPublikasi(arg0);
            return result;
        }
    }
    async addValidator(arg0: CreateInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addValidator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addValidator(arg0);
            return result;
        }
    }
    async deleteFooterLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFooterLink(arg0);
            return result;
        }
    }
    async deletePenerimaBantuan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePenerimaBantuan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePenerimaBantuan(arg0);
            return result;
        }
    }
    async deletePengaduan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePengaduan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePengaduan(arg0);
            return result;
        }
    }
    async deletePublikasi(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublikasi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublikasi(arg0);
            return result;
        }
    }
    async deleteValidator(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteValidator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteValidator(arg0);
            return result;
        }
    }
    async getAllFooterLinks(): Promise<Array<T__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFooterLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFooterLinks();
            return result;
        }
    }
    async getAllPenerimaBantuan(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPenerimaBantuan();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPenerimaBantuan();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPengaduan(): Promise<Array<T__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPengaduan();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPengaduan();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublikasi(): Promise<Array<T__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublikasi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublikasi();
            return result;
        }
    }
    async getAllValidators(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllValidators();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllValidators();
            return result;
        }
    }
    async getFooterLinkById(arg0: bigint): Promise<T__4> {
        if (this.processError) {
            try {
                const result = await this.actor.getFooterLinkById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFooterLinkById(arg0);
            return result;
        }
    }
    async getPenerimaBantuanById(arg0: bigint): Promise<T__3> {
        if (this.processError) {
            try {
                const result = await this.actor.getPenerimaBantuanById(arg0);
                return from_candid_T__3_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPenerimaBantuanById(arg0);
            return from_candid_T__3_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPenerimaBantuanByJenis(arg0: string): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPenerimaBantuanByJenis(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPenerimaBantuanByJenis(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPenerimaBantuanByStatus(arg0: Status__1): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPenerimaBantuanByStatus(to_candid_Status__1_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPenerimaBantuanByStatus(to_candid_Status__1_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPengaduanById(arg0: bigint): Promise<T__2> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengaduanById(arg0);
                return from_candid_T__2_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengaduanById(arg0);
            return from_candid_T__2_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublikasiById(arg0: bigint): Promise<T__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublikasiById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublikasiById(arg0);
            return result;
        }
    }
    async getValidatorById(arg0: bigint): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidatorById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidatorById(arg0);
            return result;
        }
    }
    async isAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async updateFooterLink(arg0: UpdateInput__4): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFooterLink(arg0);
            return result;
        }
    }
    async updatePenerimaBantuan(arg0: UpdateInput__3): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePenerimaBantuan(to_candid_UpdateInput__3_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePenerimaBantuan(to_candid_UpdateInput__3_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePengaduan(arg0: UpdateInput__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePengaduan(to_candid_UpdateInput__2_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePengaduan(to_candid_UpdateInput__2_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePublikasi(arg0: UpdateInput__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublikasi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublikasi(arg0);
            return result;
        }
    }
    async updateValidator(arg0: UpdateInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateValidator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateValidator(arg0);
            return result;
        }
    }
}
function from_candid_Status__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_T__2_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__2): T__2 {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_T__3_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__3): T__3 {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Topik_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Topik): Topik {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status__1;
    sudahDivalidasi: boolean;
    jenisBantuan: string;
    koordinatLat: number;
    koordinatLng: number;
    alamat: string;
    jumlahBantuan: bigint;
    tanggal: string;
    nama: string;
    wilayah: string;
    validatorId: [] | [string];
    keperluanBantuan: string;
    catatan: string;
}): {
    id: bigint;
    status: Status__1;
    sudahDivalidasi: boolean;
    jenisBantuan: string;
    koordinatLat: number;
    koordinatLng: number;
    alamat: string;
    jumlahBantuan: bigint;
    tanggal: string;
    nama: string;
    wilayah: string;
    validatorId?: string;
    keperluanBantuan: string;
    catatan: string;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n14(_uploadFile, _downloadFile, value.status),
        sudahDivalidasi: value.sudahDivalidasi,
        jenisBantuan: value.jenisBantuan,
        koordinatLat: value.koordinatLat,
        koordinatLng: value.koordinatLng,
        alamat: value.alamat,
        jumlahBantuan: value.jumlahBantuan,
        tanggal: value.tanggal,
        nama: value.nama,
        wilayah: value.wilayah,
        validatorId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.validatorId)),
        keperluanBantuan: value.keperluanBantuan,
        catatan: value.catatan
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    topik: _Topik;
    tanggal: string;
    nama: string;
    judul: string;
    deskripsi: string;
    catatan: string;
    kontak: string;
}): {
    id: bigint;
    status: Status;
    topik: Topik;
    tanggal: string;
    nama: string;
    judul: string;
    deskripsi: string;
    catatan: string;
    kontak: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n20(_uploadFile, _downloadFile, value.status),
        topik: from_candid_Topik_n22(_uploadFile, _downloadFile, value.topik),
        tanggal: value.tanggal,
        nama: value.nama,
        judul: value.judul,
        deskripsi: value.deskripsi,
        catatan: value.catatan,
        kontak: value.kontak
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diproses: null;
} | {
    menunggu: null;
} | {
    didistribusikan: null;
}): Status__1 {
    return "diproses" in value ? Status__1.diproses : "menunggu" in value ? Status__1.menunggu : "didistribusikan" in value ? Status__1.didistribusikan : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diproses: null;
} | {
    baru: null;
} | {
    selesai: null;
}): Status {
    return "diproses" in value ? Status.diproses : "baru" in value ? Status.baru : "selesai" in value ? Status.selesai : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lainnya: null;
} | {
    bantuan: null;
} | {
    pengungsian: null;
} | {
    infrastruktur: null;
} | {
    bencana: null;
} | {
    kesehatan: null;
}): Topik {
    return "lainnya" in value ? Topik.lainnya : "bantuan" in value ? Topik.bantuan : "pengungsian" in value ? Topik.pengungsian : "infrastruktur" in value ? Topik.infrastruktur : "bencana" in value ? Topik.bencana : "kesehatan" in value ? Topik.kesehatan : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__3>): Array<T__3> {
    return value.map((x)=>from_candid_T__3_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__2>): Array<T__2> {
    return value.map((x)=>from_candid_T__2_n18(_uploadFile, _downloadFile, x));
}
function to_candid_CreateInput__2_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInput__2): _CreateInput__2 {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CreateInput__3_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInput__3): _CreateInput__3 {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Topik_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topik): _Topik {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInput__2_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInput__2): _UpdateInput__2 {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInput__3_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInput__3): _UpdateInput__3 {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status__1;
    sudahDivalidasi: boolean;
    jenisBantuan: string;
    koordinatLat: number;
    koordinatLng: number;
    alamat: string;
    jumlahBantuan: bigint;
    tanggal: string;
    nama: string;
    wilayah: string;
    validatorId?: string;
    keperluanBantuan: string;
    catatan: string;
}): {
    id: bigint;
    status: _Status__1;
    sudahDivalidasi: boolean;
    jenisBantuan: string;
    koordinatLat: number;
    koordinatLng: number;
    alamat: string;
    jumlahBantuan: bigint;
    tanggal: string;
    nama: string;
    wilayah: string;
    validatorId: [] | [string];
    keperluanBantuan: string;
    catatan: string;
} {
    return {
        id: value.id,
        status: to_candid_Status__1_n3(_uploadFile, _downloadFile, value.status),
        sudahDivalidasi: value.sudahDivalidasi,
        jenisBantuan: value.jenisBantuan,
        koordinatLat: value.koordinatLat,
        koordinatLng: value.koordinatLng,
        alamat: value.alamat,
        jumlahBantuan: value.jumlahBantuan,
        tanggal: value.tanggal,
        nama: value.nama,
        wilayah: value.wilayah,
        validatorId: value.validatorId ? candid_some(value.validatorId) : candid_none(),
        keperluanBantuan: value.keperluanBantuan,
        catatan: value.catatan
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status;
    topik: Topik;
    tanggal: string;
    nama: string;
    judul: string;
    deskripsi: string;
    catatan: string;
    kontak: string;
}): {
    id: bigint;
    status: _Status;
    topik: _Topik;
    tanggal: string;
    nama: string;
    judul: string;
    deskripsi: string;
    catatan: string;
    kontak: string;
} {
    return {
        id: value.id,
        status: to_candid_Status_n7(_uploadFile, _downloadFile, value.status),
        topik: to_candid_Topik_n9(_uploadFile, _downloadFile, value.topik),
        tanggal: value.tanggal,
        nama: value.nama,
        judul: value.judul,
        deskripsi: value.deskripsi,
        catatan: value.catatan,
        kontak: value.kontak
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topik): {
    lainnya: null;
} | {
    bantuan: null;
} | {
    pengungsian: null;
} | {
    infrastruktur: null;
} | {
    bencana: null;
} | {
    kesehatan: null;
} {
    return value == Topik.lainnya ? {
        lainnya: null
    } : value == Topik.bantuan ? {
        bantuan: null
    } : value == Topik.pengungsian ? {
        pengungsian: null
    } : value == Topik.infrastruktur ? {
        infrastruktur: null
    } : value == Topik.bencana ? {
        bencana: null
    } : value == Topik.kesehatan ? {
        kesehatan: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    diproses: null;
} | {
    menunggu: null;
} | {
    didistribusikan: null;
} {
    return value == Status__1.diproses ? {
        diproses: null
    } : value == Status__1.menunggu ? {
        menunggu: null
    } : value == Status__1.didistribusikan ? {
        didistribusikan: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    diproses: null;
} | {
    baru: null;
} | {
    selesai: null;
} {
    return value == Status.diproses ? {
        diproses: null
    } : value == Status.baru ? {
        baru: null
    } : value == Status.selesai ? {
        selesai: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
